application: vn-app
version: 1-0
runtime: python27
threadsafe: true
api_version: 1

builtins:
- remote_api: on
#- appstats: on

libraries:
- name: jinja2
  version: "latest"
- name: webapp2
  version: "2.5.1"

handlers:

- url: /assets
  static_dir: client/docs/assets

- url: /js
  static_dir: client/js

- url: /templates
  static_dir: client/docs/templates

- url: /prototypes
  static_dir: client/docs/prototypes

# services

- url: /service/rpc/record.*
  script: vertnet.service.record.rpc

- url: /service/api/record
  script: vertnet.service.record.api

- url: /service/organization.*
  script: vertnet.service.organization.rpc

- url: /api/search.*
  script: vertnet.api.search.handler

- url: /api/organization.*
  script: vertnet.api.organization.rpc

- url: /api/stats.*
  script: vertnet.api.stats.rpc

- url: /.*
  script: app.handler
  #login: admin
