application: vertnet-portal
version: 0-0-2-wip
runtime: python27
threadsafe: true
api_version: 1

builtins:
- remote_api: on
#- appstats: on

libraries:
- name: jinja2
  version: "latest"
- name: webapp2
  version: "2.5.1"

handlers:

- url: /css
  static_dir: client/vertnet/css

- url: /vertnet
  static_dir: client/vertnet

- url: /img
  static_dir: client/vertnet/img

- url: /prototypes
  static_dir: client/docs/prototypes

# backends

# services

- url: /service/download.*
  script: vertnet.service.download.api

- url: /apitracker.*
  script: vertnet.service.tracker.api

- url: /service/rpc/record.*
  script: vertnet.service.record.rpc

- url: /service/organization.*
  script: vertnet.service.organization.rpc

- url: /api/search.*
  script: vertnet.api.search.handler

- url: /api/organization.*
  script: vertnet.api.organization.rpc

- url: /api/stats.*
  script: vertnet.api.stats.rpc

- url: /.*
  script: app.handler
  login: admin
