application: vertnet-portal
version: wip
runtime: python27
threadsafe: true
api_version: 1


# includes:
# - mapreduce/include.yaml

libraries:
- name: jinja2
  version: "latest"
- name: webapp2
  version: "2.5.1"

handlers:

# DEV
- url: /css
  static_dir: client/vertnet/css
- url: /fonts
  static_dir: client/vertnet/fonts
- url: /vertnet
  static_dir: client/vertnet
- url: /vertnet/lib
  static_dir: client/vertnet/lib
- url: /vertnet/app
  static_dir: client/vertnet/app
- url: /vertnet/views
  static_dir: client/vertnet/app/views
- url: /vertnet/models
  static_dir: client/vertnet/app/models
- url: /img
  static_dir: client/vertnet/img
- url: /prototypes
  static_dir: client/docs/prototypes

# # HACK for requirejs optimization bug.  
# - url: /*./css
#   static_dir: client/vertnet/css
# - url: /*./fonts
#   static_dir: client/vertnet/fonts
# - url: /*./vertnet
#   static_dir: client/vertnet
# - url: /*./vertnet/lib
#   static_dir: client/vertnet/lib
# - url: /*./vertnet/app
#   static_dir: client/vertnet/app
# - url: /*./vertnet/views
#   static_dir: client/vertnet/app/views
# - url: /*./vertnet/models
#   static_dir: client/vertnet/app/models
# - url: /*./img
#   static_dir: client/vertnet/img
# - url: /*./prototypes
#   static_dir: client/docs/prototypes
# # HACK for requirejs optimization bug.  

# # PRODUCTION
# - url: /css
#   static_dir: www-built/vertnet/css
# - url: /fonts
#   static_dir: www-built/vertnet/fonts
# - url: /vertnet
#   static_dir: www-built/vertnet
# - url: /vertnet/lib
#   static_dir: www-built/vertnet/lib
# - url: /vertnet/app
#   static_dir: www-built/vertnet/app
# - url: /vertnet/views
#   static_dir: www-built/vertnet/app/views
# - url: /vertnet/models
#   static_dir: www-built/vertnet/app/models
# - url: /img
#   static_dir: www-built/vertnet/img
# - url: /prototypes
#   static_dir: www-built/docs/prototypes

# # HACK for requirejs optimization bug.  
# - url: /*./css
#   static_dir: www-built/vertnet/css
# - url: /*./fonts
#   static_dir: www-built/vertnet/fonts
# - url: /*./vertnet
#   static_dir: www-built/vertnet
# - url: /*./vertnet/lib
#   static_dir: www-built/vertnet/lib
# - url: /*./vertnet/app
#   static_dir: www-built/vertnet/app
# - url: /*./vertnet/views
#   static_dir: www-built/vertnet/app/views
# - url: /*./vertnet/models
#   static_dir: www-built/vertnet/app/models
# - url: /*./img
#   static_dir: www-built/vertnet/img
# - url: /*./prototypes
#   static_dir: www-built/docs/prototypes
# # HACK for requirejs optimization bug. 


# - url: /css
#   static_dir: www-built/vertnet/css

# - url: /fonts
#   static_dir: www-built/vertnet/fonts

# - url: /vertnet
#   static_dir: www-built/vertnet

# - url: /vertnet/lib
#   static_dir: www-built/vertnet/lib

# - url: /o/vertnet/lib
#   static_dir: www-built/vertnet/lib

# - url: /p/vertnet/lib
#   static_dir: www-built/vertnet/lib

# - url: /vertnet/app
#   static_dir: www-built/vertnet/app

# - url: /vertnet/views
#   static_dir: www-built/vertnet/app/views

# - url: /vertnet/models
#   static_dir: www-built/vertnet/app/models

# - url: /img
#   static_dir: www-built/vertnet/img

# - url: /prototypes
#   static_dir: www-built/docs/prototypes


# backends

# services

- url: /service/download.*
  script: vertnet.service.download.api

- url: /apitracker.*
  script: vertnet.service.tracker.api

- url: /service/rpc/record.*
  script: vertnet.service.record.rpc

- url: /service/organization.*
  script: vertnet.service.organization.rpc

- url: /api/search.*
  script: vertnet.api.search.handler

- url: /api/organization.*
  script: vertnet.api.organization.rpc

- url: /api/stats.*
  script: vertnet.api.stats.rpc

# - url: /mapreduce(/.*)?
#   script: mapreduce/main.py
#   login: admin

- url: /.*
  script: app.handler
